version: "3.8"
services:
  rec_backend:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
